"""create onboarding_sessions table

Revision ID: 7551f5352046
Revises: 0af4ef948dc4
Create Date: 2026-02-21 09:46:48.878281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7551f5352046'
down_revision: Union[str, None] = '0af4ef948dc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onboarding_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('repository', sa.String(), nullable=True),
    sa.Column('api_endpoints', sa.String(), nullable=True),
    sa.Column('auth_method', sa.String(), nullable=True),
    sa.Column('auth_details', sa.String(), nullable=True),
    sa.Column('test_output_folder', sa.String(), nullable=True),
    sa.Column('test_output_format', sa.String(), nullable=True),
    sa.Column('test_descriptions', sa.String(), nullable=True),
    sa.Column('additional_context', sa.String(), nullable=True),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('onboarding_sessions')
    # ### end Alembic commands ###
